/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Servlets;

import Clases.detalleTest;
import ConexionesBD.Test_RealizadoBD;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Vector;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Ricardo Ramirez
 */
@WebServlet(name = "Guarda_Servlet", urlPatterns = {"/Guarda_Servlet"})
public class Guarda_Servlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            
            HttpSession session = request.getSession();

            Test_RealizadoBD tr = new Test_RealizadoBD();
            //instancio el objeto de la clase   
            //para asginar el nuevo codigo de test 
            int codigoT = tr.getCodigoDelTest(); // conecto a la base y llamo al metodo para mandar el codigo al detalle 
            String codigoU = (String) session.getAttribute("codigoU");//recupero el codigo de usuario que se establecio en "Logueo_Servlet"
            int codigoUser = Integer.parseInt(codigoU); //tramsformo en entero para que lo pueda recivir la base 

            //out.print(codigoT);
            Vector vDetalle = new Vector();
            detalleTest od;
            String p1 = request.getParameter("1");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(1);
            od.setRespuesta(p1);
            vDetalle.addElement(od);

            // session.setAttribute("vectorDetalle", vDetalle);
            String p2 = request.getParameter("2");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(2);
            od.setRespuesta(p2);
            vDetalle.addElement(od);
            // session.setAttribute("vectorDetalle", vDetalle);

            String p3 = request.getParameter("3");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(3);
            od.setRespuesta(p3);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p4 = request.getParameter("4");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(4);
            od.setRespuesta(p4);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p5 = request.getParameter("5");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(5);
            od.setRespuesta(p5);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p6 = request.getParameter("6");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(6);
            od.setRespuesta(p6);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p7 = request.getParameter("7");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(7);
            od.setRespuesta(p7);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p8 = request.getParameter("8");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(8);
            od.setRespuesta(p8);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p9 = request.getParameter("9");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(9);
            od.setRespuesta(p9);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p10 = request.getParameter("10");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(10);
            od.setRespuesta(p10);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p11 = request.getParameter("11");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(11);
            od.setRespuesta(p11);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p12 = request.getParameter("12");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(12);
            od.setRespuesta(p12);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p13 = request.getParameter("13");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(13);
            od.setRespuesta(p13);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p14 = request.getParameter("14");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(14);
            od.setRespuesta(p14);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p15 = request.getParameter("15");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(15);
            od.setRespuesta(p15);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p16 = request.getParameter("16");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(16);
            od.setRespuesta(p16);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p17 = request.getParameter("17");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(17);
            od.setRespuesta(p17);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p18 = request.getParameter("18");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(18);
            od.setRespuesta(p18);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p19 = request.getParameter("19");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(19);
            od.setRespuesta(p19);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p20 = request.getParameter("20");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(20);
            od.setRespuesta(p20);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p21 = request.getParameter("21");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(21);
            od.setRespuesta(p21);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p22 = request.getParameter("22");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(22);
            od.setRespuesta(p22);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p23 = request.getParameter("23");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(23);
            od.setRespuesta(p23);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p24 = request.getParameter("24");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(24);
            od.setRespuesta(p24);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p25 = request.getParameter("25");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(25);
            od.setRespuesta(p25);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p26 = request.getParameter("26");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(26);
            od.setRespuesta(p26);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p27 = request.getParameter("27");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(27);
            od.setRespuesta(p27);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p28 = request.getParameter("28");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(28);
            od.setRespuesta(p28);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p29 = request.getParameter("29");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(29);
            od.setRespuesta(p29);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p30 = request.getParameter("30");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(30);
            od.setRespuesta(p30);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p31 = request.getParameter("31");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(31);
            od.setRespuesta(p31);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p32 = request.getParameter("32");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(32);
            od.setRespuesta(p32);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p33 = request.getParameter("33");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(33);
            od.setRespuesta(p33);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p34 = request.getParameter("34");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(34);
            od.setRespuesta(p34);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p35 = request.getParameter("35");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(35);
            od.setRespuesta(p35);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p36 = request.getParameter("36");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(36);
            od.setRespuesta(p36);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p37 = request.getParameter("37");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(37);
            od.setRespuesta(p37);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p38 = request.getParameter("38");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(38);
            od.setRespuesta(p38);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p39 = request.getParameter("39");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(39);
            od.setRespuesta(p39);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p40 = request.getParameter("40");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(40);
            od.setRespuesta(p40);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p41 = request.getParameter("41");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(41);
            od.setRespuesta(p41);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p42 = request.getParameter("42");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(42);
            od.setRespuesta(p42);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p43 = request.getParameter("43");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(43);
            od.setRespuesta(p43);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p44 = request.getParameter("44");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(44);
            od.setRespuesta(p44);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p45 = request.getParameter("45");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(45);
            od.setRespuesta(p45);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p46 = request.getParameter("46");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(46);
            od.setRespuesta(p46);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p47 = request.getParameter("47");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(47);
            od.setRespuesta(p47);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            String p48 = request.getParameter("48");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(48);
            od.setRespuesta(p48);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p49 = request.getParameter("49");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(49);
            od.setRespuesta(p49);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p50 = request.getParameter("50");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(50);
            od.setRespuesta(p50);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p51 = request.getParameter("51");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(51);
            od.setRespuesta(p51);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p52 = request.getParameter("52");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(52);
            od.setRespuesta(p52);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p53 = request.getParameter("53");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(53);
            od.setRespuesta(p53);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p54 = request.getParameter("54");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(54);
            od.setRespuesta(p54);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p55 = request.getParameter("55");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(55);
            od.setRespuesta(p55);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p56 = request.getParameter("56");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(56);
            od.setRespuesta(p56);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p57 = request.getParameter("57");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(57);
            od.setRespuesta(p57);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p58 = request.getParameter("58");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(58);
            od.setRespuesta(p58);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p59 = request.getParameter("59");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(59);
            od.setRespuesta(p59);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p60 = request.getParameter("60");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(60);
            od.setRespuesta(p60);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p61 = request.getParameter("61");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(61);
            od.setRespuesta(p61);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p62 = request.getParameter("62");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(62);
            od.setRespuesta(p62);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p63 = request.getParameter("63");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(63);
            od.setRespuesta(p63);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p64 = request.getParameter("64");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(64);
            od.setRespuesta(p64);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p65 = request.getParameter("65");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(65);
            od.setRespuesta(p65);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p66 = request.getParameter("66");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(66);
            od.setRespuesta(p66);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p67 = request.getParameter("67");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(67);
            od.setRespuesta(p67);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p68 = request.getParameter("68");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(68);
            od.setRespuesta(p68);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p69 = request.getParameter("69");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(69);
            od.setRespuesta(p69);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p70 = request.getParameter("70");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(70);
            od.setRespuesta(p70);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p71 = request.getParameter("71");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(71);
            od.setRespuesta(p71);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p72 = request.getParameter("72");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(72);
            od.setRespuesta(p72);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p73 = request.getParameter("73");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(73);
            od.setRespuesta(p73);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p74 = request.getParameter("74");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(74);
            od.setRespuesta(p74);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p75 = request.getParameter("75");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(75);
            od.setRespuesta(p75);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p76 = request.getParameter("76");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(76);
            od.setRespuesta(p76);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p77 = request.getParameter("77");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(77);
            od.setRespuesta(p77);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p78 = request.getParameter("78");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(78);
            od.setRespuesta(p78);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p79 = request.getParameter("79");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(79);
            od.setRespuesta(p79);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p80 = request.getParameter("80");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(80);
            od.setRespuesta(p80);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p81 = request.getParameter("81");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(81);
            od.setRespuesta(p81);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p82 = request.getParameter("82");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(82);
            od.setRespuesta(p82);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p83 = request.getParameter("83");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(83);
            od.setRespuesta(p83);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p84 = request.getParameter("84");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(84);
            od.setRespuesta(p84);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p85 = request.getParameter("85");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(85);
            od.setRespuesta(p85);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p86 = request.getParameter("86");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(86);
            od.setRespuesta(p86);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p87 = request.getParameter("87");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(87);
            od.setRespuesta(p87);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p88 = request.getParameter("88");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(88);
            od.setRespuesta(p88);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p89 = request.getParameter("89");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(89);
            od.setRespuesta(p89);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p90 = request.getParameter("90");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(90);
            od.setRespuesta(p90);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p91 = request.getParameter("91");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(91);
            od.setRespuesta(p91);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p92 = request.getParameter("92");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(92);
            od.setRespuesta(p92);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p93 = request.getParameter("93");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(93);
            od.setRespuesta(p93);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p94 = request.getParameter("94");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(94);
            od.setRespuesta(p94);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p95 = request.getParameter("95");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(95);
            od.setRespuesta(p95);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p96 = request.getParameter("96");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(96);
            od.setRespuesta(p96);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p97 = request.getParameter("97");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(97);
            od.setRespuesta(p97);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p98 = request.getParameter("98");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(98);
            od.setRespuesta(p98);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p99 = request.getParameter("99");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(99);
            od.setRespuesta(p99);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p100 = request.getParameter("100");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(100);
            od.setRespuesta(p100);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p101 = request.getParameter("101");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(101);
            od.setRespuesta(p101);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p102 = request.getParameter("102");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(102);
            od.setRespuesta(p102);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p103 = request.getParameter("103");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(103);
            od.setRespuesta(p103);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p104 = request.getParameter("104");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(104);
            od.setRespuesta(p104);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p105 = request.getParameter("105");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(105);
            od.setRespuesta(p105);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p106 = request.getParameter("106");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(106);
            od.setRespuesta(p106);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p107 = request.getParameter("107");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(107);
            od.setRespuesta(p107);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p108 = request.getParameter("108");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(108);
            od.setRespuesta(p108);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p109 = request.getParameter("109");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(109);
            od.setRespuesta(p109);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p110 = request.getParameter("110");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(110);
            od.setRespuesta(p110);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p111 = request.getParameter("111");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(111);
            od.setRespuesta(p111);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p112 = request.getParameter("112");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(112);
            od.setRespuesta(p112);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p113 = request.getParameter("113");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(113);
            od.setRespuesta(p113);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p114 = request.getParameter("114");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(114);
            od.setRespuesta(p114);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p115 = request.getParameter("115");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(115);
            od.setRespuesta(p115);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p116 = request.getParameter("116");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(116);
            od.setRespuesta(p116);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p117 = request.getParameter("117");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(117);
            od.setRespuesta(p117);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p118 = request.getParameter("118");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(118);
            od.setRespuesta(p118);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p119 = request.getParameter("119");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(119);
            od.setRespuesta(p119);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p120 = request.getParameter("120");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(120);
            od.setRespuesta(p120);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p121 = request.getParameter("121");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(121);
            od.setRespuesta(p121);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p122 = request.getParameter("122");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(122);
            od.setRespuesta(p122);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p123 = request.getParameter("123");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(123);
            od.setRespuesta(p123);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p124 = request.getParameter("124");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(124);
            od.setRespuesta(p124);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p125 = request.getParameter("125");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(125);
            od.setRespuesta(p125);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p126 = request.getParameter("126");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(126);
            od.setRespuesta(p126);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p127 = request.getParameter("127");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(127);
            od.setRespuesta(p127);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p128 = request.getParameter("128");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(128);
            od.setRespuesta(p128);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p129 = request.getParameter("129");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(129);
            od.setRespuesta(p129);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p130 = request.getParameter("130");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(130);
            od.setRespuesta(p130);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p131 = request.getParameter("131");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(131);
            od.setRespuesta(p131);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p132 = request.getParameter("132");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(132);
            od.setRespuesta(p132);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p133 = request.getParameter("133");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(133);
            od.setRespuesta(p133);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p134 = request.getParameter("134");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(134);
            od.setRespuesta(p134);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p135 = request.getParameter("135");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(135);
            od.setRespuesta(p135);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p136 = request.getParameter("136");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(136);
            od.setRespuesta(p136);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p137 = request.getParameter("137");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(137);
            od.setRespuesta(p137);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p138 = request.getParameter("138");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(138);
            od.setRespuesta(p138);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p139 = request.getParameter("139");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(139);
            od.setRespuesta(p139);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p140 = request.getParameter("140");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(140);
            od.setRespuesta(p140);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p141 = request.getParameter("141");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(141);
            od.setRespuesta(p141);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p142 = request.getParameter("142");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(142);
            od.setRespuesta(p142);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p143 = request.getParameter("143");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(143);
            od.setRespuesta(p143);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p144 = request.getParameter("144");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(144);
            od.setRespuesta(p144);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p145 = request.getParameter("145");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(145);
            od.setRespuesta(p145);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p146 = request.getParameter("146");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(146);
            od.setRespuesta(p146);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p147 = request.getParameter("147");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(147);
            od.setRespuesta(p147);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p148 = request.getParameter("148");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(148);
            od.setRespuesta(p148);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p149 = request.getParameter("149");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(149);
            od.setRespuesta(p149);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p150 = request.getParameter("150");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(150);
            od.setRespuesta(p150);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p151 = request.getParameter("151");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(151);
            od.setRespuesta(p151);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p152 = request.getParameter("152");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(152);
            od.setRespuesta(p152);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p153 = request.getParameter("153");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(153);
            od.setRespuesta(p153);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p154 = request.getParameter("154");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(154);
            od.setRespuesta(p154);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p155 = request.getParameter("155");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(155);
            od.setRespuesta(p155);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p156 = request.getParameter("156");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(156);
            od.setRespuesta(p156);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p157 = request.getParameter("157");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(157);
            od.setRespuesta(p157);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p158 = request.getParameter("158");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(158);
            od.setRespuesta(p158);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p159 = request.getParameter("159");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(159);
            od.setRespuesta(p159);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p160 = request.getParameter("160");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(160);
            od.setRespuesta(p160);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p161 = request.getParameter("161");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(161);
            od.setRespuesta(p161);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p162 = request.getParameter("162");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(162);
            od.setRespuesta(p162);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p163 = request.getParameter("163");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(163);
            od.setRespuesta(p163);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p164 = request.getParameter("164");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(164);
            od.setRespuesta(p164);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p165 = request.getParameter("165");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(165);
            od.setRespuesta(p165);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p166 = request.getParameter("166");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(166);
            od.setRespuesta(p166);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p167 = request.getParameter("167");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(167);
            od.setRespuesta(p167);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p168 = request.getParameter("168");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(168);
            od.setRespuesta(p168);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p169 = request.getParameter("169");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(169);
            od.setRespuesta(p169);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p170 = request.getParameter("170");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(170);
            od.setRespuesta(p170);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p171 = request.getParameter("171");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(171);
            od.setRespuesta(p171);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p172 = request.getParameter("172");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(172);
            od.setRespuesta(p172);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p173 = request.getParameter("173");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(173);
            od.setRespuesta(p173);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p174 = request.getParameter("174");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(174);
            od.setRespuesta(p174);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p175 = request.getParameter("175");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(175);
            od.setRespuesta(p175);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p176 = request.getParameter("176");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(176);
            od.setRespuesta(p176);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p177 = request.getParameter("177");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(177);
            od.setRespuesta(p177);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p178 = request.getParameter("178");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(178);
            od.setRespuesta(p178);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p179 = request.getParameter("179");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(179);
            od.setRespuesta(p179);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p180 = request.getParameter("180");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(180);
            od.setRespuesta(p180);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p181 = request.getParameter("181");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(181);
            od.setRespuesta(p181);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p182 = request.getParameter("182");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(182);
            od.setRespuesta(p182);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p183 = request.getParameter("183");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(183);
            od.setRespuesta(p183);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p184 = request.getParameter("184");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(184);
            od.setRespuesta(p184);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p185 = request.getParameter("185");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(185);
            od.setRespuesta(p185);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p186 = request.getParameter("186");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(186);
            od.setRespuesta(p186);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);
            String p187 = request.getParameter("187");
            od = new detalleTest();
            od.setCodigoTest(codigoT);
            od.setCodigoPregunta(187);
            od.setRespuesta(p187);
            vDetalle.addElement(od);
            //session.setAttribute("vectorDetalle", vDetalle);

            // Vector vd=(Vector)session.getAttribute("vectorDetalle");
            tr.registrarTestRealizados(codigoT, codigoUser);
           
            for (int i = 0; i < vDetalle.size(); i++) {
                detalleTest dp = (detalleTest) vDetalle.elementAt(i);
                tr.registrarDetalleTest(dp.codigoTest, dp.codigoPregunta, dp.respuesta);
                //out.print(dp.codigoTest+"      "+dp.codigoPregunta+"      "+dp.respuesta);
            }
            tr.actualizaEstadoEncuesta(1,codigoUser);// se actualiza el estado de la escuesta                       
            vDetalle.removeAllElements();
            
            
            response.sendRedirect("preguntas2.jsp?msj=hecho");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
